def draw_road():
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    print("| i |")
    return
